Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/fedora-43"
  config.vm.network "public_network"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  ## SHELL PRIVILEGIADO
  config.vm.provision "shell", inline: <<-SHELL
    dnf update -y
    dnf upgrade -y
    dnf install -y curl git gcc gcc-c++ make wget ca-certificates
    
    # Grupo wheel = sudo no Fedora
    usermod -aG wheel vagrant
    id vagrant
    
    ## ADD MIRAK
    cp -r /vagrant/mirak-app /home/vagrant/
    chmod +x /home/vagrant/mirak-app/* 2>/dev/null || true
    
    # ADD TRIVY
    Fedora usa .rpm em vez de .deb
    wget https://github.com/aquasecurity/trivy/releases/download/v0.70.0/trivy_0.70.0_Linux-64bit.rpm
    rpm -ivh trivy_0.70.0_Linux-64bit.rpm
    rm trivy_0.70.0_Linux-64bit.rpm
    
    # ADD CVE-BIN-TOOLS
    dnf install -y python3-pip python3-devel
    pip3 install cve-bin-tool   
  SHELL

  ## SHELL non-root
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    echo 'source $HOME/.cargo/env' >> $HOME/.bashrc
    source $HOME/.cargo/env
    cargo install routinator@0.8.3
    echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $HOME/.bashrc
  SHELL
end
