Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20250126.1"
  config.vm.network "public_network"

 config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  ## SHELL PRIVILEGIADO
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt full-upgrade -y
    apt install -y curl git build-essential sudo wget apt-transport-https ca-certificates software-properties-common
    usermod -aG sudo vagrant
    id vagrant
    
    ## ADD MIRAK
    cp -r /vagrant/mirak-app /home/vagrant/
    chmod +x /home/vagrant/mirak-app/* 2>/dev/null || true
    
    ## ADD TRIVY
    wget https://github.com/aquasecurity/trivy/releases/download/v0.70.0/trivy_0.70.0_Linux-64bit.deb
    dpkg -i trivy_0.70.0_Linux-64bit.deb
    rm trivy_0.70.0_Linux-64bit.deb
    
    ## ADD CVE-BIN-TOOLS
    apt install -y python3-pip python3-venv pipx
    pipx install cve-bin-tool
    export PATH=$PATH:/root/.local/bin
    sudo -u vagrant pipx ensurepath
    sudo -u vagrant pipx install cve-bin-tool
    ln -sf /root/.local/bin/cve-bin-tool /usr/local/bin/cve-bin-tool
    ln -sf /home/vagrant/.local/bin/cve-bin-tool /usr/local/bin/cve-bin-tool-vagrant 2>/dev/null || true
    echo 'export PATH=$PATH:/home/vagrant/.local/bin' >> /home/vagrant/.bashrc
    echo 'export PATH=$PATH:/root/.local/bin' >> /root/.bashrc

    ## ADD VULS
    # INSTALL Go
    wget https://go.dev/dl/go1.26.2.linux-amd64.tar.gz
    tar -C /usr/local -xzf go1.26.2.linux-amd64.tar.gz
    rm go1.26.2.linux-amd64.tar.gz
    echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile.d/go.sh
    export PATH=$PATH:/usr/local/go/bin
    
    # INSTALL DEPENDENCIES Vuls
    apt install -y sqlite3 gcc make
    
    # INSTALL Vuls
    cd /opt
    git clone https://github.com/future-architect/vuls.git
    cd vuls
    make install
    ln -sf /root/go/bin/vuls /usr/local/bin/vuls
    mkdir -p /opt/vuls/config /opt/vuls/results
    chmod -R 755 /opt/vuls
    cd / && rm -rf /opt/vuls-src 2>/dev/null || true 
  SHELL

## SHELL non-root
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    echo 'source $HOME/.cargo/env' >> $HOME/.bashrc
    source $HOME/.cargo/env
    cargo install routinator@0.8.3
    echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $HOME/.bashrc
  SHELL
end
